distribuidor/urls.py
from django.conf.urls import url
from .views import CreateDistribuidor, ListaDistribuidor, DetalleView, ActualizarView, EliminarView

urlpatterns = [url(r'^lista_distribuidores/$', ListaDistribuidor.as_view(), name='lista_distribuidores'),
               url(r'^detalle_distribuidores/(?P<pk>\d+)/$', DetalleView.as_view(),
                   name='detalle_distribuidores'),
               url(r'^actualizar_distribuidores/(?P<pk>\d+)/$', ActualizarView.as_view(),
                   name="actualizar_distribuidores"),
               url(r'^eliminar_distribuidor/(?P<pk>\d+)/$', EliminarView.as_view(),
                   name="eliminar_distribuidor"),
               url(r'^create_distribuidor/$', CreateDistribuidor.as_view(), name='create_distribuidor'),
               ]

ferreteria/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # productos
    url(r'^', include('medicamentos.urls', namespace="medicamentos_app")),

    # agregar ventas.
    url(r'^ventas/', include('ventas.urls', namespace="ventas_app")),

    # login-users
    url(r'^', include('users.urls', namespace='users_app')),

    # CLientes
    url(r'^', include('clientes.urls', namespace='clientes_app')),

    url(r'^', include('distribuidor.urls', namespace='distribuidores_app')),

    # compras
    url(r'^', include('compras.urls', namespace='compras_app')),
    # compras
    url(r'^', include('laboratorio.urls', namespace='laboratorios_app')),

    url(r'^todolist/', include('inline.urls', namespace='todolist')),

    # factura
    url(r'^', include('factura.urls', namespace='factura_app')),

]

users/urls.py
from django.conf.urls import url
from .views import Home, userlogin, LogOut

urlpatterns = [url(r'^$', userlogin, name="login"),
               url(r'^salir/$', LogOut, name='logout'),
               # principal
               url(r'^home', Home.as_view(), name='home'),
               ]

templates/distribuidores/base_distribuidores.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css %}

   <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="/static/plugins/datatables/dataTables.bootstrap.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/static/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{% endblock css %}
{% block js %}
   
    <!-- jQuery 2.1.4 -->
    <script src="/static/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <!-- DataTables -->
    <script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="/static/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/static/plugins/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/static/dist/js/app.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/static/dist/js/demo.js"></script>
    <!-- page script -->
    <script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>
{% endblock js %}

templates/distribuidores/create_update_distribuidores.html
{% extends "distribuidores/base_distribuidores.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %} 
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
         <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Distribuidores
          </h1>
          <ol class="breadcrumb">
            <li><a href="{% url 'users_app:home' %}"><i class="fa fa-dashboard"></i>Inicio</a></li>
            <li><a href="{% url 'distribuidores_app:lista_distribuidores' %}">Distribuidores</a></li>
            <li class="active">Nuevo Distribuidor</li>
          </ol>
        </section>
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
             
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div><!-- /.box-tools -->
                       
            </div><!-- /.box-header -->
              <div class="box-body"> 
    
                    <div class="row">
                      <div class="col-lg-12">
                        <form class="form-horizontal" method="post">
                            {% csrf_token %} 
                            <div class="row">                              
                                <div class="col-xs-12 col-sm-10">  
                                     
                                    <div class="form-group has-success has-feedback  {% if form.nombre.errors %} has-error {% endif %}">
                                        <label class="control-label col-sm-2" for="inputSuccess3">{{ form.nombre.label_tag }}</label>
                                        <div class="col-sm-6">                                        
                                            <input type="text" id="disabledTextInput" name="nombre" class="form-control" value='{% if form.nombre.value %}{{ form.nombre.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.nombre.errors.as_text}}' autofocus='true'>                                       
                                        </div>
                                    </div> 
                                 
  
                                    <div class="form-group has-success has-feedback  {% if form.ruc.errors %} has-error {% endif %}">
                                        <label class="control-label col-sm-2" for="inputSuccess3">{{ form.ruc.label_tag }}</label>
                                        <div class="col-sm-6">                                        
                                            <input type="text" id="disabledTextInput" name="ruc" class="form-control" value='{% if form.ruc.value %}{{ form.ruc.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.ruc.errors.as_text}}' autofocus='true'>                                       
                                        </div>
                                    </div> 
                                    <div class="form-group has-success has-feedback  {% if form.direccion.errors %} has-error {% endif %}">
                                        <label class="control-label col-sm-2" for="inputSuccess3">{{ form.direccion.label_tag }}</label>
                                        <div class="col-sm-6">                                        
                                            <input type="text" id="disabledTextInput" name="direccion" class="form-control" value='{% if form.direccion.value %}{{ form.direccion.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.direccion.errors.as_text}}' autofocus='true'>                                       
                                        </div>
                                    </div> 
                                     <div class="form-group has-success has-feedback  {% if form.telefono.errors %} has-error {% endif %}">
                                        <label class="control-label col-sm-2" for="inputSuccess3">{{ form.telefono.label_tag }}</label>
                                        <div class="col-sm-6">                                        
                                            <input type="number" id="disabledTextInput" name="telefono" class="form-control" value='{% if form.telefono.value %}{{ form.telefono.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.telefono.errors.as_text}}' autofocus='true'>                                       
                                        </div>
                                       </div>  
                                                                     
                                </div>                                                        
                            </div> <!--<div class="row"> -->                                        
                                <div class="panel-footer color-footer">
                                    <button type="submit" class="btn btn-primary">
                                                 Grabar
                                    </button>
                                </div>               
                        </form>
                      </div>
                    </div><!--/.row-->
            </div><!-- /.box body -->
          </div><!-- /.box info -->
          </div><!--col-->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->
{% include "footer.html" %}    
 {% endblock producto %}
{% endblock content %}

templates/distribuidores/detalle_distribuidores.html
{% extends "distribuidores/base_distribuidores.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %} 
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
          
            <div class="box-header with-border">
          		<a href="{% url 'distribuidores_app:lista_distribuidores' %}" class="btn btn-success">
            		<span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>              
              		<div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->            
            </div><!-- /.box-header -->
              <div class="box-body">
                  <table class="table table-striped table table-hover ">
	                    <tbody> 
	                          <tr class="success">
	                          	  <td><strong>Nombre:</strong></td>
	                              <td>{{ object.nombre }} </td> 
	                           </tr>	                           
	                           	                           <tr class="success">
	                           	  <td><strong>RUC:</strong></td>
	                              <td>{{ object.ruc }}</td>                              
	                           </tr>
	                           <tr class="success">
	                           	  <td><strong>Dirección:</strong> </td>
	                              <td>{{ object.direccion}}</td>                  
	                           </tr> 
                             <tr class="success">
                                <td><strong>Teléfono:</strong> </td>
                                <td>{{ object.telefono}}</td>                  
                             </tr>                           
	                    </tbody>
	               	</table>                                 
              </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% include "footer.html" %}    
 {% endblock producto %}
{% endblock content %}

templates/distribuidores/eliminar_distribuidores.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %} 
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
              <i class="fa fa-bullhorn"></i>             
            </div><!-- /.box-header -->
              <div class="box-body">
                  <div class="callout callout-danger">                    
                    <h1> Eliminar</h1>
                    <form method="POST">
                    {% csrf_token %}
                      <p class="coloreliminar">¿Desea eliminar al Distribuidor "{{ object.nombre }}?</p>
                      <input type="submit" value="Sí" class="btn btn-warning"> 
                      <a href="{% url 'distribuidores_app:lista_distribuidores' %}" class="btn btn-info">No</a>
                    </form>                        
                  </div>                                   
              </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% include "footer.html" %}    
 {% endblock producto %}
{% endblock content %}

templates/distribuidores/lista_distribuidores.html
{% extends "distribuidores/base_distribuidores.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}    
    <div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Distribuidores
          </h1>
          <ol class="breadcrumb">
            <li><a href="{% url 'users_app:home' %}"><i class="fa fa-dashboard"></i>Inicio</a></li>
            <li class="active">Distribuidores</li>
            <li><a href="{% url 'distribuidores_app:create_distribuidor' %}">Nuevo Distribuidor</a></li>
            
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">

                <div class="box box-primary">
                  <div class="box-header with-border">
                    <h3 class="box-title"><a href="{% url 'distribuidores_app:create_distribuidor' %}" class="btn btn-success">
                      Nuevo Distribuidor
                    </a></h3>
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                  </div><!-- /.box-header -->
                  <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                     <tr>
                        <th>N°</th>                      
                        <th>Nombre</th> 
                        <th>Ruc</th>                              
                        <th>Dirección</th>
                        <th>Teléfono</th>
                        <th>Acciones</th>                       
                      </tr>
                    </thead>
                    <tbody>
                    
                     {% for d in distribuidores %} 
                        <tr> 
                          <td>{{ forloop.counter}}</td>                         
                          <td>{{ d.nombre }} </td> 
                          <td>{{ d.ruc }}</td>                              
                          <td>{{ d.direccion}}</td>
                          <td>{{d.telefono}}</td>
                          <td class="text-right">
                                  {% if user.is_authenticated %}
                                  <a href="{% url 'distribuidores_app:detalle_distribuidores' d.id %} " class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                                  {% endif %}

                                  <a href="{% url 'distribuidores_app:actualizar_distribuidores' d.id  %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                  {% for group in user.groups.all %}
                                     {% if group.name == 'administrador' %}
                                  <a href="{% url 'distribuidores_app:eliminar_distribuidor' d.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a> 
                                  {% endif %}
                                  {% endfor %}
                            </td>                      
                              
                          </tr>
                      {% endfor %}
                    </tbody>

                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
{% include "footer.html" %}    
 {% endblock producto %}
{% endblock content %}