clientes/urls.py
from django.conf.urls import url
from .views import CreateCliente, ListaCliente, DetalleView, ActualizarView, EliminarView

urlpatterns = [
    url(r'^lista_clientes/$', ListaCliente.as_view(), name='lista_clientes'),
    url(r'^detalle_cliente/(?P<pk>\d+)/$', DetalleView.as_view(), name='detalle_cliente'),
    url(r'^actualizar_clientes/(?P<pk>\d+)/$', ActualizarView.as_view(), name="actualizar_clientes"),
    url(r'^eliminar_cliente/(?P<pk>\d+)/$', EliminarView.as_view(), name="eliminar_cliente"),
    url(r'^create_clientes/$', CreateCliente.as_view(), name='create_clientes'),
]

compras/urls.py
from django.conf.urls import url
from .views import ListaCompras, realizar_compra, reportecompras  # , generar_reporte_lista_compras
from django.views.generic import TemplateView

urlpatterns = [
    url(r'compras/realizar_compra/$', realizar_compra, name="realizar_compra"),
    url(r'compras/confirmacion_compra$', TemplateView.as_view(template_name="compras/confirmacion_compra.html")),
    url(r'compras/lista_compras/$', ListaCompras.as_view(), name='lista_compras'),
    url(r'compras/reporte_compras/(?P<pk>\d+)/$', reportecompras, name='reporte_compras'),
    # url(r'compras/generar_reporte_lista_compras/$', generar_reporte_lista_compras,
    #    name='generar_reporte_lista_compras'),
]

factura/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'factura/lista_ventas/$', views.ListaVentas.as_view(), name='lista_ventas'),
    url(r'^factura/venta$', views.facturaCrear, name="factura_venta"),
    url(r'^factura/buscar_cliente$', views.buscarCliente),
    url(r'^factura/buscar_producto$', views.buscarProducto),
    url(r'^factura/consultar$', views.consultarFactura, name="consultar_factura"),
    #url(r'factura/generar_reporte_factura/$', views.generar_pdf, name='generar_reporte_factura'),
    url(r'factura/reporte_ventas/(?P<pk>\d+)/$', views.reporteventas, name='reporte_ventas'),
]

ferreteria/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # productos
    url(r'^', include('medicamentos.urls', namespace="medicamentos_app")),

    # agregar ventas.
    url(r'^ventas/', include('ventas.urls', namespace="ventas_app")),

    # login-users
    url(r'^', include('users.urls', namespace='users_app')),

    # CLientes
    url(r'^', include('clientes.urls', namespace='clientes_app')),

    url(r'^', include('distribuidor.urls', namespace='distribuidores_app')),

    # compras
    url(r'^', include('compras.urls', namespace='compras_app')),
    # compras
    url(r'^', include('laboratorio.urls', namespace='laboratorios_app')),

    url(r'^todolist/', include('inline.urls', namespace='todolist')),

    # factura
    url(r'^', include('factura.urls', namespace='factura_app')),

]

laboratorio/urls.py
from django.conf.urls import url
from .views import CreateLaboratorio, ListaLaboratorio, DetalleView, ActualizarView, EliminarView

urlpatterns = [
    url(r'^lista_laboratorios/$', ListaLaboratorio.as_view(), name='lista_laboratorios'),
    url(r'^detalle_laboratorios/(?P<pk>\d+)/$', DetalleView.as_view(), name='detalle_laboratorios'),
    url(r'^actualizar_laboratorios/(?P<pk>\d+)/$', ActualizarView.as_view(),
        name="actualizar_laboratorios"),
    url(r'^eliminar_laboratorios/(?P<pk>\d+)/$', EliminarView.as_view(),
        name="eliminar_laboratorios"),
    url(r'^create_laboratorios/$', CreateLaboratorio.as_view(), name='create_laboratorios'),
]

users/urls.py
from django.conf.urls import url
from .views import Home, userlogin, LogOut

urlpatterns = [url(r'^$', userlogin, name="login"),
               url(r'^salir/$', LogOut, name='logout'),
               # principal
               url(r'^home', Home.as_view(), name='home'),
               ]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>{% block title %}{% endblock title %}</title></head>
	{% block css %}{% endblock css %}
 <body class="hold-transition skin-blue sidebar-mini">
	
	{% block content %}
	{% endblock content %}

	{% block js %}
	{% endblock js %}
</html>

templates/footer.html
 <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 1.0
        </div>
        <strong>Desarrollado por <a href="http://pasionmarketingweb.com/">Wilder Hernández García</a>.</strong>
      </footer>

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
          <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
          <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <!-- Home tab content -->
          <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                    <p>Will be 23 on April 24th</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-user bg-yellow"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
                    <p>New phone +1(800)555-1234</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
                    <p>nora@example.com</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-file-code-o bg-green"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
                    <p>Execution time 5 seconds</p>
                  </div>
                </a>
              </li>
            </ul><!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Custom Template Design
                    <span class="label label-danger pull-right">70%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Update Resume
                    <span class="label label-success pull-right">95%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Laravel Integration
                    <span class="label label-warning pull-right">50%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Back End Framework
                    <span class="label label-primary pull-right">68%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                  </div>
                </a>
              </li>
            </ul><!-- /.control-sidebar-menu -->

          </div><!-- /.tab-pane -->
          <!-- Stats tab content -->
          <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
          <!-- Settings tab content -->
          <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
              <h3 class="control-sidebar-heading">General Settings</h3>
              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Report panel usage
                  <input type="checkbox" class="pull-right" checked>
                </label>
                <p>
                  Some information about this general settings option
                </p>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Allow mail redirect
                  <input type="checkbox" class="pull-right" checked>
                </label>
                <p>
                  Other sets of options are available
                </p>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Expose author name in posts
                  <input type="checkbox" class="pull-right" checked>
                </label>
                <p>
                  Allow the user to show his name in blog posts
                </p>
              </div><!-- /.form-group -->

              <h3 class="control-sidebar-heading">Chat Settings</h3>

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Show me as online
                  <input type="checkbox" class="pull-right" checked>
                </label>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Turn off notifications
                  <input type="checkbox" class="pull-right">
                </label>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Delete chat history
                  <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                </label>
              </div><!-- /.form-group -->
            </form>
          </div><!-- /.tab-pane -->
        </div>
      </aside><!-- /.control-sidebar -->
      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div><!-- ./wrapper -->

templates/nav.html
  <meta charset="UTF-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<div class="wrapper">
      <header class="main-header">
        <!-- Logo -->
        <a href="#" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>F</b>arma</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Farma</b>Salud</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">           
            
              <!-- User Account: style can be found in dropdown.less -->
               <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="{{ MEDIA_URL }}{{ user.avatar }}" class="img-circle" alt="User Image" height="20" width="20" > 
                  <span class="hidden-xs">{{ user.username|capfirst }} {{ user.last_name|capfirst }}</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <img src="{{ MEDIA_URL }}{{ user.avatar }}" class="img-circle" alt="User Image" > 
                     <p>
                       {{ user.username|capfirst }} {{ user.last_name|capfirst }}
                  
                    </p>
                  </li>
  
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <!--<a href="#" class="btn btn-default btn-flat">Profile</a>-->
                    </div>
                    <div class="pull-right">
                      <a href="{% url 'users_app:logout' %}" class="btn btn-default btn-flat">Salir</a>
                    </div>
                  </li>
                </ul>
              </li>
              <!-- Control Sidebar Toggle Button -->
              <!--<li>
                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
              </li>-->
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
            <img src="{{ MEDIA_URL }}{{ user.avatar }}" class="img-circle" alt="User Image" > 
            </div>
            <div class="pull-left info">
              <p>{{ user.username|capfirst }} {{ user.last_name|capfirst }}</p>
              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>

          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>

         
            
            <li class="treeview">
              <a href="#">
                <i class="fa fa-child"></i> <span>Clientes</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li class="active"><a href="{% url 'clientes_app:lista_clientes' %}"><i class="fa fa-check-square"></i> Lista</a></li>
                <li><a href="{% url 'clientes_app:create_clientes' %}"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>
              </ul>
            </li>

            <li class="treeview">
              <a href="#">
                <i class="fa fa-child"></i> <span>Distribuidores</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li class="active"><a href="{% url 'distribuidores_app:lista_distribuidores' %}"><i class="fa fa-check-square"></i> Lista</a></li>
                <li><a href="{% url 'distribuidores_app:create_distribuidor' %}"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-child"></i> <span>Laboratorios</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li class="active"><a href="{% url 'laboratorios_app:lista_laboratorios' %}"><i class="fa fa-check-square"></i> Lista</a></li>
                <li><a href="{% url 'laboratorios_app:create_laboratorios' %}"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>
              </ul>
            </li>

            <li class="treeview">
              <a href="#">
                <i class="fa fa-medkit"></i>
                <span>Medicamentos</span>
                <span class="label label-primary pull-right">2</span>
              </a>
              <ul class="treeview-menu">
                <li><a href="{% url 'medicamentos_app:lista_medicamentos' %}"><i class="fa fa fa-check-square"></i> Lista</a></li>                
                <li><a href="{% url 'medicamentos_app:create_medicamentos' %}"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>               
              </ul>
            </li>

     
            <li class="treeview">
              <a href="#">
                <i class="fa fa-pie-chart"></i>
                <span>Compras</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{% url 'compras_app:lista_compras' %}"><i class="fa fa-circle-o"></i> Listado de Compras</a></li>
                <li><a href="{% url 'compras_app:realizar_compra' %}"><i class="fa fa-circle-o"></i> Realizar Compras</a></li>
{#                <li><a href="{% url 'compras_app:generar_reporte_lista_compras' %}"><i class="fa fa-circle-o"></i> Reportes Compras</a></li>                #}
              </ul>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-laptop"></i>
                <span>Ventas</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
              <li><a href="{% url 'factura_app:lista_ventas' %}"><i class="fa fa-circle-o"></i> Lista Ventas</a></li>
               
                <li><a href="{% url 'factura_app:factura_venta' %}"><i class="fa fa-circle-o"></i> Realizar Venta</a></li>
                <li><a href="{% url 'factura_app:consultar_factura' %}"><i class="fa fa-circle-o"></i> Consultar Venta</a></li>
{#                <li><a href="{% url 'factura_app:generar_reporte_factura' %}"><i class="fa fa-circle-o"></i> Reporte Venta</a></li>#}
               
              </ul>
            </li>

        <!--    <li class="header">Alertas</li>
            <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Medicamentos</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Compras</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Ventas</span></a></li>      -->
        </section>
        <!-- /.sidebar -->
      </aside>
      